- name: Install Nginx
  apt:
    name: nginx
    state: present
  when: ansible_os_family == 'Debian'

- name: generate site Config:
  template:
    src: site.conf.j2
    dest: /etc/nginx/site-enabled/site.conf
    owner: root
    group: root
    mode: 0744

- name: generate index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0744

- name: Enable nginx service
  systemd:
    name: nginx
    daemon_reload: yes
    enabled: yes
    state: started